# Generated by Django 4.2.4 on 2023-10-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('czas_trwania', models.IntegerField()),
                ('schroniska', models.TextField()),
                ('notatka_o_szycie', models.TextField()),
            ],
        ),
    ]
