# Generated by Django 4.2.4 on 2023-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasa',
            name='kolor_szlaku',
            field=models.CharField(default='Domyślny Kolor', max_length=50),
        ),
        migrations.AddField(
            model_name='trasa',
            name='pasmo_gorskie',
            field=models.CharField(default='Tatry', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trasa',
            name='wysokosc_szczytu',
            field=models.IntegerField(default=2499),
            preserve_default=False,
        ),
    ]
