# Generated by Django 4.2.4 on 2023-10-18 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gory', '0002_trasa_kolor_szlaku_trasa_pasmo_gorskie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasa',
            name='godzina_wyjscia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasa',
            name='godzina_zakonczenia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasa',
            name='punkt_na_mapie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trasa',
            name='ukonczona',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trasa',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trasy', to=settings.AUTH_USER_MODEL),
        ),
    ]
