# Generated by Django 4.2.4 on 2023-10-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gory', '0003_trasa_godzina_wyjscia_trasa_godzina_zakonczenia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Szczyt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='trasa',
            name='wybrany_szczyt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gory.szczyt'),
        ),
    ]
