# Generated by Django 4.2.4 on 2023-10-18 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gory', '0004_szczyt_trasa_wybrany_szczyt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trasa',
            name='godzina_wyjscia',
        ),
        migrations.RemoveField(
            model_name='trasa',
            name='godzina_zakonczenia',
        ),
        migrations.RemoveField(
            model_name='trasa',
            name='punkt_na_mapie',
        ),
        migrations.RemoveField(
            model_name='trasa',
            name='ukonczona',
        ),
        migrations.RemoveField(
            model_name='trasa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trasa',
            name='wybrany_szczyt',
        ),
        migrations.AddField(
            model_name='szczyt',
            name='godzina_wyjscia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='szczyt',
            name='godzina_zakonczenia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='szczyt',
            name='punkt_na_mapie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='szczyt',
            name='ukonczona',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='szczyt',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trasy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='szczyt',
            name='wybrany_szczyt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gory.szczyt'),
        ),
    ]
