# Generated by Django 4.2.4 on 2023-10-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gory', '0005_remove_trasa_godzina_wyjscia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wyprawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_szczytu', models.CharField(max_length=100)),
                ('godzina_wyjscia', models.DateTimeField(blank=True, null=True)),
                ('godzina_zakonczenia', models.DateTimeField(blank=True, null=True)),
                ('ukonczona', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyprawy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
