# Generated by Django 4.2.4 on 2023-10-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gory', '0008_trasa_identyfikator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgloszenie',
            options={'ordering': ['-godzina_wyruszenia']},
        ),
    ]
