# Generated by Django 4.2.4 on 2023-10-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gory', '0009_alter_zgloszenie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddzialRatowniczy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kontakt', models.CharField(max_length=100)),
                ('dostepnosc', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='wyruszyl_na_pomoc',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ZespolRatowniczy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('dostepnosc', models.BooleanField(default=True)),
                ('oddzial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gory.oddzialratowniczy')),
            ],
        ),
    ]
