# Generated by Django 4.2.4 on 2023-11-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gory', '0012_zgloszenie_historia_oddzialow_alter_zgloszenie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddzialratowniczy',
            name='przypisane_zgloszenia',
            field=models.ManyToManyField(blank=True, related_name='przypisane_oddzialy', to='Gory.zgloszenie'),
        ),
    ]
